### ISSUE TITLE
[bug] analog input not working (or improve api)

### ISSUE THREAD

**Issue by mutmedia** [plunderludics/unity-hawk#24]
either it doesn't work or i don't know what values i should be sending, either way feels broken

**Comment by mutmedia** [comment]
its actually working, but it sends os input EG "wmouse x" or the controller connected to the pc, not "P1 X Axis"

**Comment by mutmedia** [comment]
still can be improved to not have to be multiplied by 10000

**Comment by iatenothingbutriceforthreedays** [comment]
If we're rehauling the whole inputsystem (to send direct as platform input) then this is not needed right?

**Comment by iatenothingbutriceforthreedays** [comment]
@mutmedia can I close this or remove from v1?
